### ISSUE TITLE
Custom `renderer` seems to break multi-line syntax highlighting

### ISSUE THREAD

**Issue by ibrahima** [react-syntax-highlighter/react-syntax-highlighter#122]
Hi!

I'm not sure if I'm doing something wrong, or if there's an issue with how custom renderers build up the DOM structure, but multi-line constructs (eg. multi-line comments) don't get syntax highlighted correctly when you use a custom renderer function. You can actually see the issue on the virtualized demo here:

http://conor.rodeo/react-syntax-highlighter/demo/virtualized.html

Notice that for the multi-line comments, only the first and last lines are in grey, while the lines in between are actually the regular text color.

Or with this Python snippet:

```python
'''
Single quoted doc string
'''

"""
Multi quoted doc string
"""
```

![image](https://user-images.githubusercontent.com/47774/41942794-c0b8902e-7955-11e8-9dc9-9a6fee01a726.png)

I noticed that if you don't override the renderer parameter, the code inside is nested inside the formatting tags, but I'm guessing that since in the virtualized case you would want to render each line independently, each line is within its own context and the formatting for a line does not extend past that line.

Hmm... looking at https://github.com/conorhastings/react-syntax-highlighter/blob/master/src/highlight.js , it might be a side effect of `wrapLines` being set to true... I set it to false, and now the syntax highlighting is correct, but my (custom renderer's) line numbers are wrong because the multiline statements get considered as one line. Will investigate further...

![image](https://user-images.githubusercontent.com/47774/41942747-7c85fc7a-7955-11e8-9cc3-efb88ea10494.png)

**Comment by ibrahima** [comment]
It seems like perhaps for the custom renderer case (with `wrapLines` enabled), you might need to keep track of any formatted contexts that the parser is currently inside, and wrap those around the line as otherwise rendered. I'm not sure whether that would deal with something like

```js
/**
 * comment
 */ function() {}
```
though.

**Comment by conorhastings** [comment]
hey sorry just saw this! i'm not totally sure what you mean by this -- , you might need to keep track of any formatted contexts -- could you give more of another example

**Comment by ibrahima** [comment]
Oh no worries, I might just be making up terminology to try to express what I meant. I guess what I was suggesting was something like, if you start a comment block (or any other multi-line block), until it's finished you would wrap any following lines with the comment block tags until you find the end of the block. But the start and end of a block don't necessarily have to coincide with the start and end of lines so it's not that simple.

I'll have to take a look at the internals again to see if I can figure out a way to handle this issue. It seems like it might be a little tricky to do correctly, since breaking things up by lines loses the tree structure.

**Comment by ibrahima** [comment]
Wow, thanks, that was actually really fast! I actually think something might still be wrong, because now it seems like if you start a multi-line string, somehow everything in the entire file gets the string class.

Example that's fine (no multi-line strings)

```python
from __future__ import print_function
import re

STR = "Normal string"

class Example(object):
    """Test class"""
    def foo(self):
        x = 2
        return x
```

![image](https://user-images.githubusercontent.com/47774/42364804-57268108-80b1-11e8-8b6c-920eb454b85b.png)

```python
from __future__ import print_function
import re

STR = """This string takes multiple lines.

Does it mess up the highlighting?
"""
class Example(object):
    """Test class"""
    def foo(self):
        x = 2
        return x
```

![image](https://user-images.githubusercontent.com/47774/42364764-2fc81c5c-80b1-11e8-9403-b51bd44cb3c6.png)

**Comment by conorhastings** [comment]
can you post what the second sreenshot should look like, thanks.

**Comment by ibrahima** [comment]
Both snippets should have the same coloring, (i.e. everything besides `STR = ...` should be the same). In the second one all the text has hljs-string applied to it for some reason (I've disabled inline styles because I use a different color scheme) but all the green text that's not inside a string should be black.

Thanks!

**Comment by conorhastings** [comment]
any chance you could post your code?

**Comment by ibrahima** [comment]
To follow back up with this, the issue still exists. You can see it on the "virtualized" demo (the old demo link no longer works) by editing the React props with dev tools. I added this into the code and it does not get syntax highlighted correctly.

```js
/*
 This is a multiline comment
 It gets highlighted correctly normally
 But not with a custom renderer
*/
```

![image](https://github.com/react-syntax-highlighter/react-syntax-highlighter/assets/47774/2f57ea08-8409-48d1-8f6e-9eae2c16d268)

(I had to insert `\n`s to the React prop to actually render line breaks, so `/*\n This is a multiline comment\n It gets highlighted correctly normally\n But not with a custom renderer\n
*/`)

For the default demo it works fine

![image](https://github.com/react-syntax-highlighter/react-syntax-highlighter/assets/47774/214d388a-fe9a-4a76-abc9-c6ee10065ba7)
