### ISSUE TITLE
Improve build system

### ISSUE THREAD

**Issue by dmtrKovalenko** [react-syntax-highlighter/react-syntax-highlighter#167]
**Is your feature request related to a problem? Please describe.**
You have a lot of big files, that are exported and do not add a way to easily import them. All files exists in the `/dist/` but docs say to import them directly.

**Describe the solution you'd like**
1. Publish only bundled folder as we are doing in [material-ui-pickers](https://github.com/dmtrKovalenko/material-ui-pickers/tree/develop/lib)
2. Provide `esm` build with [rollup](https://rollupjs.org/guide/en) to be sure treeshaking works if we are importing from entry point (index.js file)

I can help with a build system and open a PR. Cause we are using this project and it is really nice.

**Comment by conorhastings** [comment]
Would appreciate any help you could offer!

**Comment by conorhastings** [comment]
@marcodejongh can you take a look at this if you get a chance, I know you did a lot of the more recent buiid stuff

Thanks for the PR

**Comment by marcodejongh** [comment]
@conorhastings sure will do

**Comment by simmerer** [comment]
Associated PR was closed, closing this issue
