### ISSUE TITLE
linestyle not working as expected

### ISSUE THREAD

**Issue by jemodyMS** [react-syntax-highlighter/react-syntax-highlighter#206]
1. What is the difference between lineProps and lineStyle?
2. I have used lineStyle as described in the example and as I saw it in issue #76 but it does not work for me. This is what my code looks like -
`<SyntaxHighlighter
                language='csharp'
                showLineNumbers={true}
                style={docco}
                wrapLines
                lineProps={(lineNumber: number) => {
                    const style = { display: '', backgroundColor: '' };
                    if (ADDED == lineNumber) {
                        style.display = 'block';
                        style.backgroundColor = '#dbffdb';
                    }
                    else if (REMOVED == lineNumber) {
                        style.display = 'block';
                        style.backgroundColor = '#ffecec';
                    }
                    return style;
                }}>
                {codeSnippet}
            </SyntaxHighlighter>`

The output is as you see in the below image. ADDED is set to 1 and REMOVED is set to 2. Can you help me find what I am missing? Version is ^11.0.2
![image](https://user-images.githubusercontent.com/42416262/63199133-bb4fa400-c031-11e9-9365-ef254ca307e9.png)

**Comment by conorhastings** [comment]
can you post your full code snippet

**Comment by alixander** [comment]
It's renamed to lineNumberProps
