### ISSUE TITLE
lineStyle/lineProp not working

### ISSUE THREAD

**Issue by carlosmiei** [react-syntax-highlighter/react-syntax-highlighter#208]
**Describe the bug**
I tried to highlight specific lines following the example on the page but neither of the props worked..

**To Reproduce**
```

                            <SyntaxHighlighter
                                wrapLines={true}
                                showLineNumbers
                                language="javascript"
                                style={docco}
                                lineStyle={(lineNumber) => { const style = { display: 'block', color: '#ff0000' };return style; }}
                            >
                                {this.state.code}
                            </SyntaxHighlighter>

```
**Expected behavior**
I was expecting the color change to red.

**Screenshots**
![bug2](https://user-images.githubusercontent.com/43336371/63416748-efdbab00-c3f7-11e9-8ae8-46e82a719f2c.png)
![bug](https://user-images.githubusercontent.com/43336371/63416749-f0744180-c3f7-11e9-9b66-1a9ef914571c.png)

However if I use the same code with the lineNumberStyle prop  works.

![bug3](https://user-images.githubusercontent.com/43336371/63417114-91fb9300-c3f8-11e9-99be-290d80486912.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Chrome

**Comment by samselikoff** [comment]
Believe it's been changed to `lineProps`. Try changing it to that and returning an object like `{ style: { display: 'block', color: '#ff0000' }}`

**Comment by SalahAdDin** [comment]
@samselikoff @carlosmiei 
yeah, it was changed to `lineProps` even when in the documentation and the `typescript` file say it is still available.
