### ISSUE TITLE
Changelog is missing for version 11

### ISSUE THREAD

**Issue by stof** [react-syntax-highlighter/react-syntax-highlighter#214]
Neither the changelog file in the repo nor the github release page provides a changelog for version 11.

**Comment by madou** [comment]
Yeah. What broke? What changed? Anything we should know?

@conorhastings is there any secret changelog somewhere?

**Comment by kylepeeler** [comment]
Bump, can we get an updated changelog? I don't feel comfortable updating this package until I know what changes/what is breaking so that I can fix it... @conorhastings

**Comment by kylepeeler** [comment]
Bump any updates? We have seen two major versions and no direction to what has changed or an upgrade path necessary if there are any regressions... @conorhastings

**Comment by conorhastings** [comment]
I try to get to these thing when i can im currently working a new full time job and dont havee time to be eproactivee with theese issues apologies

**Comment by kylepeeler** [comment]
If we can't get a changelog... can u let us know what exactly could lead to a breaking change when upgrading from v10 -> v12? I would really like to upgrade but without knowing this it won't be :/ thanks.

**Comment by cheshrkat** [comment]
For those following this one, there do seem to be notes for 13+, just not in the changelog: https://github.com/react-syntax-highlighter/react-syntax-highlighter/releases ...contents of 11 and 12 remain a mystery, haven't found any notes for those.

**Comment by simmerer** [comment]
Yep, since I've been contributing I've tried to add complete notes in each release. I'll migrate those to the changelog as well.

For 11 and 12, I might be able to piece them together by digging through commit history.

**Comment by cheshrkat** [comment]
@simmerer thanks so much for doing this, it's super helpful and much appreciated :)

**Comment by kylepeeler** [comment]
@simmerer Thank you for addressing this! ❤️
