### ISSUE TITLE
Jest test fails because failing import

### ISSUE THREAD

**Issue by soosgyul** [react-syntax-highlighter/react-syntax-highlighter#221]
**Describe the bug**
I have a component called CodeDisplay. I have a very simple snapshot test, just to test that the component actually renders, but the test fails.
The test looks like this:
```import React from "react"
import renderer from "react-test-renderer"
import { CodeDisplay } from "./index"

describe("CodeDisplay", () => {
  it("renders correctly", () => {
    const tree = renderer.create(<CodeDisplay />).toJSON()
    expect(tree).toMatchSnapshot()
  })
})
```
and the relevant part of the error I'm getting is:
```Test suite failed to run

    /Users/gyula/workspace/radioplayer/bg/node_modules/react-syntax-highlighter/dist/esm/languages/hljs/javascript.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import javascript from "highlight.js/lib/languages/javascript";
                                                                                                    ^^^^^^^^^^

    SyntaxError: Unexpected identifier

      2 | import React, { useCallback, useState } from "react"
      3 | import { Light as SyntaxHighlighter } from "react-syntax-highlighter"
    > 4 | import js from "react-syntax-highlighter/dist/esm/languages/hljs/javascript"
        | ^
      5 | import docco from "react-syntax-highlighter/dist/esm/styles/hljs/docco"```

Any ideas?

**Comment by mnikkane** [comment]
Adding this (workaround) to jest config helped me in similar case:

```
   transformIgnorePatterns: [
     "/node_modules/(?!(react-syntax-highlighter)/)"
   ],
```
But I think this is just a workaround and should not be needed if all works correctly, so I think this issue is valid still.

**Comment by tommywalkie** [comment]
@soosgyul Using Jest, Enzyme and Parcel in my project, it doesn't seem like Jest recognized the content in `dist/esm` as modules, so when Jest detects an `import` statement it doesn't understand and make the test fail.
```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest)
          {import highlight from './highlight';
           ^^^^^^

    SyntaxError: Cannot use import statement outside a module

> 4  | import Prism from 'react-syntax-highlighter/dist/esm/prism'
     | ^
```

So i figured that falling back to CommonJS files in `dist/cjs` when importing what i needed (in my case I just needed `Prism`), it did the trick for both development and test environments 👍 

```js
import Prism from 'react-syntax-highlighter/dist/esm/prism' // ❌ doesn't work
import { Prism } from 'react-syntax-highlighter/dist/esm' // ❌ doesn't work
import Prism from 'react-syntax-highlighter/dist/cjs/prism' // ✅ works
import { Prism } from 'react-syntax-highlighter/dist/cjs' // ✅ works
```

**Comment by jeffreycwitt** [comment]
Had the same problem for import of "docco". 

Originally I had: 

`import { docco } from 'react-syntax-highlighter/dist/esm/styles/hljs';` (doesn't work)

Following @tommywalkie I got it work using the following import:

`import { docco } from 'react-syntax-highlighter/dist/cjs/styles/hljs';` (works)

Thanks @tommywalkie !
