### ISSUE TITLE
fontfamily style passed to codetagprops doesnot work

### ISSUE THREAD

**Issue by aravind1078** [react-syntax-highlighter/react-syntax-highlighter#225]
**Describe the bug**
when I pass font-family to the code tag props it does not set its font-family style

**To Reproduce**
pass object to codetagprops including font-family:'monaco'

**Expected behavior**
expect it to set the font-family style of what i passed it as props

**Comment by kwkr** [comment]
In my case it worked when I included it like this:
```
<SyntaxHighlighter
  codeTagProps={{
    style: {
      'font-family': 'Monaco',
    },
  }}
>
```

**Comment by simmerer** [comment]
Yep, the `style` object needs keys to be either camelCased or quoted. Either of these should work:

```javascript
style: {
  'font-family': 'Monaco'
}
```

```javascript
style: {
  fontFamily: 'Monaco'
}
```
