### ISSUE TITLE
Uncaught TypeError: hljs.getLanguage(...).rawDefinition is not a function

### ISSUE THREAD

**Issue by yyyc514** [react-syntax-highlighter/react-syntax-highlighter#226]
**Describe the bug**

Receiving the following error with Highlight.js 9.16.2.

```
Uncaught TypeError: hljs.getLanguage(...).rawDefinition is not a function
```

Reporting this on behalf of @mattwhocn.  Was originally filed against Highlight.js:

https://github.com/highlightjs/highlight.js/issues/2279

**To Reproduce**
1. Try using `react-syntax-highlighter` with Highlight.js 10.16.2
2. See issue I imagine (see additional context below)

Sorry I don't have more specific steps.

**Expected behavior**
The library works as expected without throwing the error:

```
Uncaught TypeError: hljs.getLanguage(...).rawDefinition is not a function
```

**Desktop:**
Dunno. Pretty sure this is not environment specific. (see addl. context)

**Smartphone:**
Dunno.  Pretty sure this is not environment specific. (see addl. context)

**Additional context**
You have created a very custom loading process for languages.  Newer versions of Highlight.js have stronger interconnections between languages.  `cpp` needs to be registered BEFORE `arduino` can be registered as they now depend on each other at run-time (during registration).

Not sure what might need to change to fix this, but wanted to file it here as it seems to be a problem with how you all are packaging/loading the languages.

**Comment by yyyc514** [comment]
Though actually 9.15.10 has the same dependency:

```
function(hljs) {
  var CPP = hljs.getLanguage('cpp').exports;
	return {
```

So now I guess I'm a little confused.

**Comment by yyyc514** [comment]
Ok, I'm thinking this is a lowlight issue now, sheesh.  Off to open an issue there. :)  Will link it here just incase.

**Comment by yyyc514** [comment]
https://github.com/wooorm/lowlight/issues/19

**Comment by yyyc514** [comment]
Curious: How does `build-languages-highlightjs.js` guarantee the correct load order though?  I don't see any mention of `Requires` or re-ordering the languages to load in the correct order.

Arduino will below up if it's loaded before CPP.  So not sure how this is working now?

**Comment by yyyc514** [comment]
This is what I'd expect you to see: 

https://github.com/conorhastings/react-syntax-highlighter/issues/10

**Comment by wooorm** [comment]
Should work now after updating to lowlight 1.13.0

**Comment by yyyc514** [comment]
Any idea on my ordering question?

**Comment by conorhastings** [comment]
@yyyc514 there is ordering logic, is this defined anywhere if it is i can build it in

**Comment by yyyc514** [comment]
Well it may change in the future but right now the language files are annotated in the top comment. “Requires”

Dependencies should be loaded first. Though now I’m already thinking about how we might remove this requirement.

**Comment by wooorm** [comment]
With refractor/prism it's more clear (as in, separated) than with hljs. There I use babel to inspect the languages to require and go from there.

I'd suggest using something like require or import for hljs? That's useful for tools like us and built tools internally

**Comment by yyyc514** [comment]
Long term we likely will. First we need new build system which I’ve been working on. Though eventually that gets into how do we do duplication in modules if we’re resolving dependencies at compile time not runtime. 

https://github.com/highlightjs/highlight.js/issues/2248

**Comment by yyyc514** [comment]
Is just ripping ordering from index.js not trivial?

**Comment by wooorm** [comment]
> First we need new build system which I’ve been working on

That would be awesome! Btw, I think the questions you ask there are supported by build tools like webpack (async loading), Conor is doing that here!

---

We could indeed also introduce a build step with babel in lowlight, similar to refractor, that detects e.g., [`hljs.getLanguage`](https://github.com/highlightjs/highlight.js/blob/61cd26958cff7876dfc12ccbc5c3444cd3755b6f/src/languages/arduino.js#L97) calls and creates language bundles.

Similar to the syntax tree, I’d prefer these features to go in hljs and prism though, to benefit the wider ecosystem and reduce the work I need to do!

**Comment by yyyc514** [comment]
Well, the issue [this one] with your own codebase was because you're a fork essentially.  Once we have a parse tree output you could really slim down a lot (by requiring us vs rewriting us), and then I don't think you'd run afoul of this type of issue in the future - since really your codebase would mostly disappear.  

I'm not sure why `react-syntax-highlighter` needs such a complex build system for HLJS.

**Comment by wooorm** [comment]
Again, that is exactly what I want.

react-syntax-highlighter has a build system because it [solves what your linked issue is about](https://github.com/conorhastings/react-syntax-highlighter#light-build)

**Comment by yyyc514** [comment]
But our NPM package already has requirable modules... are they going to ALL that trouble just to get the registerLanguage included in the require?  No, because then they still have to go and register it manually... I'm not sure I get the point.

Not sure why they just couldn't require our NATIVE packaged languages directly rather than wrap them all.

**Comment by yyyc514** [comment]
> Again, that is exactly what I want.

I've been working on other things but when I have a PR with the tree stuff I'll ping you and you can play with it and give feedback.

**Comment by simmerer** [comment]
Closing this issue as we've refactored our `lowlight` vs `refractor` [detection logic](https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/9fca845a4f175edd705f5cd89e7c9b5e1f966f16/src/highlight.js#L269-L298) and are no longer calling `getLanguage()` anywhere.

Did you ever get a satisfactory conclusion to this issue elsewhere, @yyyc514 ?

**Comment by yyyc514** [comment]
I only skimmed but I think my answers remain the same as before:

- Build and load a monolith (letting us handle the dependencies)
- Use the `Requires:` meta-data in the languages files to build your own dependency tree.
- Use the order of languages in the `index` file to decide "proper" load order.

Long-term we might switch to modules everywhere and move away from run-time dependencies but that's probably a 2021 thing, and I don't see a big rush. Newer work we're doing (like pulling ECMAscript out into a dependency of JS, TS, Livescript, Coffeescript, etc) is all module based rather than run-time to avoid these issues entirely.
