### ISSUE TITLE
vsDark is not exported

### ISSUE THREAD

**Issue by bencmbrook** [react-syntax-highlighter/react-syntax-highlighter#227]
`src/styles/prism/vs-dark.js` exists but isn't exported from [`src/styles/prism/index.js`](https://github.com/conorhastings/react-syntax-highlighter/blob/master/src/styles/prism/index.js)

Related to #184

**Comment by NotoriousRebel** [comment]
Any updates?

**Comment by simmerer** [comment]
I'll take a look at this one shortly!

**Comment by simmerer** [comment]
https://github.com/react-syntax-highlighter/react-syntax-highlighter/pull/283 will fix this... had to update our dependency to pull the latest commits from `prism-themes`.

Looks like `vs-dark` has been superseded by `vsc-dark-plus`.

**Comment by simmerer** [comment]
Resolved with `13.2.0` 🎉
