### ISSUE TITLE
Wrap long lines not working

### ISSUE THREAD

**Issue by imjustd** [react-syntax-highlighter/react-syntax-highlighter#235]
**Describe the bug**
Long lines can't be wrapped, when trying to do with style `white-space: pre-wrap;` on the `pre code` element the line numbers get broken.

**To Reproduce**
1. Add new SyntaxHighlighter with long code of any king
2. Set style `white-space: pre-wrap;` on the `pre code` element
3. Scroll down to the bottom and see last lines without number

**Expected behavior**
Would expect to have build-in wrap long lines properly that will correctly wrap the lines and keep the correct numbering

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser  Chrome
 - Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by mjyoung** [comment]
Curious if there are any thoughts from the team on this?

**Comment by simmerer** [comment]
@imjustd @mjyoung I haven't had a chance to try this myself yet, but does adding the `showInlineLineNumbers={true}` prop solve the issue as far as keeping line numbers correctly paired with their original lines?

**Comment by mjyoung** [comment]
@simmerer adding `showInlineLineNumbers` definitely works better than without, but then of course the text flows into what would normally be the line numbers "gutter", which is undesirable:

![image](https://user-images.githubusercontent.com/868346/92535927-fead1f80-f1fd-11ea-85ed-649d7d52b795.png)

**Comment by simmerer** [comment]
Ok, thanks for that screenshot! We can CSS around this pretty effectively.
