### ISSUE TITLE
first number will be missing when highlighter "only {number}f {number}transfer".

### ISSUE THREAD

**Issue by chiyutianyi** [react-syntax-highlighter/react-syntax-highlighter#253]
**Describe the bug**
char "2" is missing when highlighter "only 2f transfer". 

**Screenshots**
https://react-syntax-highlighter.github.io/react-syntax-highlighter/demo/
![image](https://user-images.githubusercontent.com/16610542/77536816-f1160e80-6ed7-11ea-913d-e538bc3b39d3.png)

**Comment by simmerer** [comment]
Couldn't reproduce this on 13.2.1.

<img width="993" alt="Screen Shot 2020-07-30 at 8 13 41 PM" src="https://user-images.githubusercontent.com/194735/88996181-74d67200-d2a1-11ea-9a43-02966fba79fb.png">

Try the updated demo: https://react-syntax-highlighter.github.io/react-syntax-highlighter/demo/
