### ISSUE TITLE
Component's prop with inline function renders incorrectly

### ISSUE THREAD

**Issue by NewBieBR** [react-syntax-highlighter/react-syntax-highlighter#265]
**Describe the bug**
Component's prop with inline function renders incorrectly.

**To Reproduce**
1. Go to [the official demo](https://react-syntax-highlighter.github.io/react-syntax-highlighter/demo/)
2. Use this code as source:
```
const InfiniteFeed = () => {
  return (
    <Component
      propFn={({ item }) => <a>{item}</a>}
    />
  );
};
```
3. See `propFn` brackets colors are incorrect on the right panel.

**Expected behavior**
Correct brackets colors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 83

**Comment by conorhastings** [comment]
The default demo uses hljs which does not highllight jsx try with prism 
<img width="458" alt="Screen Shot 2020-07-29 at 2 49 28 PM" src="https://user-images.githubusercontent.com/8263298/88857253-cc45e680-d1aa-11ea-8579-2e82519addae.png">

**Comment by simmerer** [comment]
@NewBieBR could you add a screenshot just so we can be sure we're talking about the same thing? I'm not sure I understand precisely what you mean by "brackets colors are incorrect".

**Comment by simmerer** [comment]
Closing as this is likely a highlighting library choice issue.

- Prism provides `jsx` as a language definition
- Highlight attempts to highlight JSX with their `javascript` definition, but it doesn't always handle JSX correctly

If you're highlighting JSX, you should probably use Prism:

```javascript
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'
```
