### ISSUE TITLE
Line number should be able to clickable  (like Github) or support custom component

### ISSUE THREAD

**Issue by kunyan** [react-syntax-highlighter/react-syntax-highlighter#270]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement a source code viewer which is similar like GitHub.
It should support highlight a single line by clicked. 

the url path should added "https://github.com/conorhastings/react-syntax-highlighter-virtualized-renderer/blob/master/package.json#L3"

If we could support multi lines selected that will be great ! example: "https://github.com/conorhastings/react-syntax-highlighter-virtualized-renderer/blob/master/package.json#L3-L15"

**Describe the solution you'd like**
If this lib could implement same feature like GitHub.

**Describe alternatives you've considered**
support use custom component for each line number, that will be great

<img width="1222" alt="Screen Shot 2020-07-09 at 2 19 40 PM" src="https://user-images.githubusercontent.com/752130/87003995-43610e00-c1ef-11ea-9087-efdeaa857858.png">

**Comment by conorhastings** [comment]
this is supported -- see issue 101
