### ISSUE TITLE
Github Pages not building properly

### ISSUE THREAD

**Issue by simmerer** [react-syntax-highlighter/react-syntax-highlighter#277]
Sorry to bother you again with another permissions request @conorhastings, but if you'd be cool with granting me `Settings`-level permissions here, I can work on why my push to `gh-pages` isn't getting built properly.

~New HTML and CSS are there in the demos, but the demo JS is all old.~

After deleting and re-pushing the `gh-pages` branch, it's all `404` :(

**Comment by conorhastings** [comment]
i temporarily removed your access and reinvited you i can only add you as a collaborator going to look into moving this project to an org

**Comment by conorhastings** [comment]
going to move to here -- https://github.com/react-syntax-highlighter/react-syntax-highlighter invited you as an owner of the org, what's your npm username i can give you access to publish as well

**Comment by simmerer** [comment]
Spectacular! I'm `simmerer` on npm as well.

**Comment by conorhastings** [comment]
@simmerer invited on npm good to close this?
