### ISSUE TITLE
Incorrect syntax highlighting for mutli-line comments

### ISSUE THREAD

**Issue by urish** [react-syntax-highlighter/react-syntax-highlighter#285]
First of all, thanks for the awesome library! I'm in the process of migrating [GoodArduinoCode](https://goodarduinocode.com) to use this library for the syntax highlighting, and `react-syntax-highlighter` looks so much more feature complete than the library I have been using before (e.g. being able to wrap each line with an element, custom line renderer...) wow 😊

## Describe the bug
In Multi-line comments, only the first and last lines are colored correctly. The remaining lines are colored as if they were not part of the comment. For instance, compare the first few lines of highlighted code [in the current version of the page](https://goodarduinocode.com/projects/simon#source-simon_ino) with [the react-syntax-highlighter version of the page](https://good-arduino-code-j405doypd.vercel.app/projects/simon#source-simon_ino):

![Issue](https://user-images.githubusercontent.com/892318/89079355-f22be080-d38e-11ea-89ba-d4e1ef597829.png)

## To Reproduce
I created a minimal stackblitz example that reproduces the issue:

https://stackblitz.com/edit/react-syntax-highlighter-issue?file=index.tsx

and a screen shot showing the line colored incorrectly in the above example:

<img src="https://user-images.githubusercontent.com/892318/89078697-8c8b2480-d38d-11ea-8583-e9b4df065497.png" width="500" alt="Reproduction on Stackblitz" />

## Expected behavior
All comment lines should be the same color (gray).

## Desktop
 - OS: Windows
 - Browser Chrome
 - Version 84.0.4147.105 (64-bit)

🙏

**Comment by simmerer** [comment]
It appears that the two-sequential-asterisk pattern you're using to open comments is causing this behavior.

In your demo link (thank you for providing that!), notice that [this comment is highlighted correctly](https://good-arduino-code-j405doypd.vercel.app/projects/simon#source-simon_ino): 

```c
/* Constants - define pin numbers for LEDs,
   buttons and speaker, and also the game tones: */
```

If `/**` should be a valid comment-opening structure for a c-like language, I think this may be an issue for the project where the `arduino` language is defined: https://github.com/highlightjs/highlight.js

We only provide a build wrapper here in `react-syntax-highlighter`. Languages are defined in the highlight (or prism) libraries.

**Comment by urish** [comment]
Hi David, thank you for looking into this!

I tried to see if the issue reproduces when using highlight.js directly, but it seems to be specific to `react-syntax-highlighter`:

* [Arduino code highlighted with highlight.js directly](https://stackblitz.com/edit/react-syntax-highlighter-issue-highlightjs?file=index.tsx) - all the comment lines are grayed out
* [JavaScript + `react-syntax-highlighter` reproduction](https://stackblitz.com/edit/react-syntax-highlighter-issue-js?file=index.tsx) - the same issue seem to affect JavaScript as well

By looking at the DOM generated, I can see at least one apparent difference that may point at the right direction:

**react-syntax-highlighter**
```html
<span style="color: rgba(149, 165, 166, 0.8);">/* This is a multi-
</span>   line comment. 
<span style="color: rgba(149, 165, 166, 0.8);">*/</span><span>
</span>
```

**highlight.js**
```html
<span class="hljs-comment">/* This is a multi-
   line comment. 
*/</span>
```

It seems like `react-syntax-highlighter` wraps the first and last lines of the comment each with a styled span, while `highlight.js` wraps the entire comment with just a single span.

**Comment by urish** [comment]
Anything I can do to help with this?

**Comment by simmerer** [comment]
Feels to me like https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/287 is related.

@urish we'd always welcome a PR if you think you've gotten to the bottom of why this is happening! I know Conor's pretty busy, and I haven't had a chance to dig into this one yet, but I'll try to get to it in the next few days.

**Comment by urish** [comment]
Thanks David! I can definitely look into it, any pointers that can help? Maybe some suspect or a good place to start looking at?

**Comment by simmerer** [comment]
Yep! https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/src/highlight.js is the crux of the processing that's custom to `react-syntax-highlighter`, and I'd probably begin with what's happening in [`createLineElement`](https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/src/highlight.js#L92)

**Comment by urish** [comment]
I think I found the issue, sent a PR with all the details (#289)
