### ISSUE TITLE
csharp hljs module has incorrect require path

### ISSUE THREAD

**Issue by mshwery** [react-syntax-highlighter/react-syntax-highlighter#294]
**Describe the bug**
Requiring `react-syntax-highlighter/dist/esm/languages/hljs/cs` fails because it is requiring a module path that does not exist: https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/languages/hljs/cs.js#L7

The correct path should target `csharp` not `cs`:
https://github.com/highlightjs/highlight.js/blob/014343e8d57f35ac6b01c619d9a3d8989de39dfe/src/languages/csharp.js

**To Reproduce**
1. import csharp via hljs: `import csharp from 'react-syntax-highlighter/dist/esm/languages/hljs/cs'`
2. try to compile your project
3. the require fails:
  ```
 ERROR  Failed to compile with 1 errors

This dependency was not found:

* highlight.js/lib/languages/cs in ./node_modules/react-syntax-highlighter/dist/esm/languages/hljs/cs.js

To install it, you can run: npm install --save highlight.js/lib/languages/cs
```

**Expected behavior**
The require should not fail.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: NA
 - Version: 

**Additional context**
`react-syntax-highlighter@13.3.1`
`highlight.js@10.1.2`

**Comment by simmerer** [comment]
Hey @mshwery, thanks for highlighting this. I probably should have called out the language-renaming changes from  `highlight.js` 10.1.x a little more emphatically in our [13.0.0 release notes](https://github.com/react-syntax-highlighter/react-syntax-highlighter/releases/tag/13.0.0).

We autogenerate our language modules from highlight, so if you want to use `react-syntax-highlighter` 13+, you'll need to change your import statement to:

```js
import csharp from 'react-syntax-highlighter/dist/esm/languages/hljs/csharp'
```

I'll work on removing any remaining traces of `cs` in our codebase to avoid any future confusion.
