### ISSUE TITLE
Poor performance on re-render

### ISSUE THREAD

**Issue by samuela** [react-syntax-highlighter/react-syntax-highlighter#302]
**Describe the bug**
Any time React does a re-render on the `SyntaxHighlighter` component, the component does a full re-parse, re-highlight of the entire document even when the document hasn't changed. The most egregious offender is [`getCodeTree`](https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/src/highlight.js#L280) and next up is [`processLines`](https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/src/highlight.js#L144).

I think the fix here is to simply wrap these in [`useMemo`](https://reactjs.org/docs/hooks-reference.html#usememo).

**To Reproduce**
1. Render a large file.
2. Note that re-renders are still very slow.

**Expected behavior**

**Screenshots**
![Screen Shot 2020-08-18 at 1 11 27 PM](https://user-images.githubusercontent.com/226872/90560903-b21d7980-e154-11ea-9e0b-cf5e1f386516.png)

Video: https://youtu.be/N01PEn3BZIk

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser Chrome, FireFox

**Additional context**

**Comment by ygorduraes** [comment]
I'm having this same problem with large files. I still haven't found a workaround for this issue.

**Comment by travisdahl** [comment]
Having the same issue. Unusable with large files.

**Comment by francostramana** [comment]
Any solution? It's really a big problem.

**Comment by karlhorky** [comment]
I think this may be fixed by #394 by @xiangst0816

This has been merged, but not yet released (maybe it will become `15.4.6`)

cc @conorhastings

**Comment by simmerer** [comment]
15.5.0 (released this morning) contains @xiangst0816 's fix from https://github.com/react-syntax-highlighter/react-syntax-highlighter/pull/394

**Comment by karlhorky** [comment]
Thanks @simmerer !

**Comment by iampava** [comment]
I don't think this is fixed. The correct solution, as mentioned here https://github.com/react-syntax-highlighter/react-syntax-highlighter/pull/303  should be `useMemo`

A hack I did in my app, that helped is to actually memoize the component myself

```jsx
const memoizedHighlighter = useMemo(
      () => (
        <SyntaxHighlighter>
          {code}
        </SyntaxHighlighter>
      ),
      [code]
    );

 return (
      <div>
        {memoizedHighlighter}
      </div>
    );
```
