### ISSUE TITLE
Why is HTML/XML language support not available?

### ISSUE THREAD

**Issue by skdcodes** [react-syntax-highlighter/react-syntax-highlighter#310]
HTML and XML are supported out of the box wtih **Prism.js** but no such language support is available in https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/AVAILABLE_LANGUAGES_PRISM.MD with this library. Is it not availale with in the library or no included in the above list?

Would be happy to create a PR! :)

**Comment by simmerer** [comment]
Thanks for mentioning this, @skdcodes!

Prism refers to HTML, XML, and a few others as `Markup`: https://prismjs.com/#supported-languages

Selecting `markup` as your highlighting language here should behave as expected: https://react-syntax-highlighter.github.io/react-syntax-highlighter/demo/prism.html

**Comment by brianfinkelstein** [comment]
FWIW, my use case for getting HTML highlighting working correctly using the standard setup (no prism) and choosing `xml` instead of `html` or `javascript`.

Demo: https://codesandbox.io/s/react-syntax-highlighter-html-u5uer
