### ISSUE TITLE
Setting wrapLines Props causes LineNumber to appear on the last line of the result.

### ISSUE THREAD

**Issue by jaime-lee** [react-syntax-highlighter/react-syntax-highlighter#321]
### **Describe the bug**

When applying wrapLines Props of SyntaxHighlighter, LineNumber is generated at the last line
(Problems that occur when showLineNumbers=false)

### **To Reproduce**

[React Source]
![image](https://user-images.githubusercontent.com/7699206/96429472-efc57e00-123b-11eb-8bcf-9741bf1cb407.png)

[Render Result]
![image](https://user-images.githubusercontent.com/7699206/96430195-d40ea780-123c-11eb-87c5-bf0e8dd9fbad.png)

### **Expected behavior**

**- There is a bug in Highlight.js**

source code : react-syntax-highlighter/src/highlight.js 

![image](https://user-images.githubusercontent.com/7699206/96431775-f73a5680-123e-11eb-9510-ee1a7970f195.png)

It is passed to lineNumber without checking whether showLineNumbers is true. 
I think it needs to be modified as follows, what do you think?

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [85.0.4183.102]

**Comment by wkk5194** [comment]
have the same condition

**Comment by conorhastings** [comment]
make sense, do you want to make a pr, since you seem to have a handle on it?

**Comment by jaime-lee** [comment]
> make sense, do you want to make a pr, since you seem to have a handle on it?

You mean the Pull Request?

I want to participate as soon as the time comes!

In addition to the wrapLine issue, there are also parts where the className of lineProps cannot be set. Shall we also look at this part?

**Comment by simmerer** [comment]
If you're interested in fixing multiple unrelated issues, it's helpful for everyone involved to provide your fixes in separate pull requests: one PR for each issue you've fixed. Thanks being excited to contribute!

**Comment by vinhnglx** [comment]
I'm facing the same issue too.
