### ISSUE TITLE
Upgrade to prism-themes@1.5.0

### ISSUE THREAD

**Issue by karlhorky** [react-syntax-highlighter/react-syntax-highlighter#327]
Hey @simmerer! 👋 

**Is your feature request related to a problem? Please describe.**

`prism-themes@1.5.0` has been released: https://github.com/PrismJS/prism-themes/pull/106#issuecomment-715928215

It contains a fix to the highlighting of diffs in the VS Code Dark Plus theme: https://github.com/PrismJS/prism-themes/pull/106#issue-508905374

**Comment by karlhorky** [comment]
Thanks @simmerer !

Is this going to be published in `15.2.2` or `15.3.0`?

Right now, `15.2.1` still has the old version: https://unpkg.com/browse/react-syntax-highlighter@15.2.1/package.json

**Comment by simmerer** [comment]
I see that Conor's also merged a few things recently... probably 15.3.0.

**Comment by simmerer** [comment]
[15.3.0 it is](https://github.com/react-syntax-highlighter/react-syntax-highlighter/releases/tag/v15.3.0)!

**Comment by karlhorky** [comment]
Great, will upgrade in the next few days, thanks!
