### ISSUE TITLE
'#' character should not start a comment  when highlighting SQL

### ISSUE THREAD

**Issue by cyrankiewicz** [react-syntax-highlighter/react-syntax-highlighter#332]
**Describe the bug**
using '#' character in sql results in the rest of the line highlighted as comment 

**To Reproduce**
1. Go to 'https://react-syntax-highlighter.github.io/react-syntax-highlighter/demo/'
2. type the following code:
```sql
select '{"foo": "bar"}'::jsonb->'foo';

select '{"foo": "bar"}'::jsonb#>'{foo}';
```
3. The first line is highlighted correctly while the other is treated as if '#' started a comment ('#>' is a JSON operator)

**Expected behavior**
'#' should not be treated as a sign that starts a comment in sql.

**Screenshots**
![image](https://user-images.githubusercontent.com/28702667/98110564-8f6f4700-1e9f-11eb-9f67-b1ffea5f6ccb.png)

**Comment by cyrankiewicz** [comment]
incidentally, github code highlighting has the same issue :angry:

**Comment by simmerer** [comment]
Thank you for calling this out, @cyrankiewicz! Unfortunately it's an issue in Highlight JS (see here: https://github.com/highlightjs/highlight.js/issues/2744).

`react-syntax-highlighter` merely imports and re-bundles language definitions from Highlight and Prism.
