### ISSUE TITLE
Please bump highlight.js to 10.4.1

### ISSUE THREAD

**Issue by aschonfeld** [react-syntax-highlighter/react-syntax-highlighter#339]
react-syntax-highlighter is an excellent package but it is causing dependabot warnings on my tools that use them because it’s using a version of highlight.js that has security vulnerablility. Thank you 🙏

**Comment by simmerer** [comment]
Should have this released tonight.

**Comment by aschonfeld** [comment]
🙏

**Comment by simmerer** [comment]
Released as `15.4.0, release notes coming in just a moment.
https://github.com/react-syntax-highlighter/react-syntax-highlighter/pull/338
