### ISSUE TITLE
Enabling line numbers shifts text over on line 10 and beyond. (see difference between line 9 and 10)

### ISSUE THREAD

**Issue by arianitu** [react-syntax-highlighter/react-syntax-highlighter#340]
**Describe the bug**
Line numbers seem to shift text to the right after line 10?

**To Reproduce**
Go to https://react-syntax-highlighter.github.io/react-syntax-highlighter/demo/

Look at line 10, why is everything shifted to the right? If you highlight the text, you can see the shift even more clearly.

**Expected behavior**
Line numbers should not affect text to the right at all.

**Screenshots**

**Desktop (please complete the following information):**
- Mac OSX
- Chrome
- 87

**Additional context**
I used the Highlight.js (default) demo.

**Comment by simmerer** [comment]
Good eye!
