### ISSUE TITLE
Can't resolve 'highlight.js/lib/languages/node-repl'

### ISSUE THREAD

**Issue by tu4mo** [react-syntax-highlighter/react-syntax-highlighter#343]
**Describe the bug**
```
Can't resolve 'highlight.js/lib/languages/node-repl' in '/*/node_modules/react-syntax-highlighter/dist/esm/async-languages'
```

**To Reproduce**
Have react-syntax-highlighter installed with other package that depends on a version of highlight.js that's fixed to <10.4.0.

**Expected behavior**
react-syntax-highlighter depends on highlight.js@[^10.4.0](https://github.com/highlightjs/highlight.js/releases/tag/10.4.0) (instead of ^10.1.1) where node-repl was added.

**Comment by aurelien-reeves** [comment]
It seems to be because of lowlight.
I had to add lowlight 1.17.0 in my package.json to make it work. Without it, it was using lowlight 1.16.0 wich seems not working with react-syntax-highlighter 15.4.1.

**Comment by aurelien-reeves** [comment]
In my yarn.lock file, lowlight@^1.14.0 is resolved to 1.16.0
Even if I add lowlight@^1.17.0, I still have the 1.16.0 installed, wich then add highlight.js@10.3.0

```
lowlight@^1.14.0:
  version "1.16.0"
  resolved "https://registry.yarnpkg.com/lowlight/-/lowlight-1.16.0.tgz#9d904370d0b20bca0893d73559cf27428fecbf7e"
  integrity sha512-ECLdzIJvBEjK4ef51sWiGZyz21yx4IEPaF/62DRxLehoOHkWqN3OsLB1GUMfc6Mcf87rR5eW7z6lI9cNEXZDsQ==
  dependencies:
    fault "^1.0.0"
    highlight.js "~10.3.0"

lowlight@^1.17.0:
  version "1.17.0"
  resolved "https://registry.yarnpkg.com/lowlight/-/lowlight-1.17.0.tgz#a1143b2fba8239df8cd5893f9fe97aaf8465af4a"
  integrity sha512-vmtBgYKD+QVNy7tIa7ulz5d//Il9R4MooOVh4nkOf9R9Cb/Dk5TXMSTieg/vDulkBkIWj59/BIlyFQxT9X1oAQ==
  dependencies:
    fault "^1.0.0"
    highlight.js "~10.4.0"
```

I don't understand why lowlight@^1.14.0 resolve in 1.16 instead of 1.17.

**Comment by aurelien-reeves** [comment]
It seems I found a way to make it work:

I have removed `lowlight` and `react-syntax-highlighter` from the dependencies in `package.json`, then executed `yarn install`. It seems to have "cleaned-up" the `yarn.lock` file.

I have also clean the cache of yarn (`yarn cache clean lowlight` and `yarn cache clean react-syntax-highlighter`). I don't know if that was actually usefull.

Then `yarn add react-syntax-highlighter` and `yarn install` again. The `yarn.lock` file now have only `lowlight@1.17.0`, and my build has passed.

**Comment by andrevenancio** [comment]
Having the same issue on a next.js project that uses this module as a dependency. I had to do something similar but using npm myself.

So `rm -rf node_modules package-lock.json .next` and then `npm install` and was able to build my next.js application after that.

**Comment by tu4mo** [comment]
I'm still getting the same error. You need to bump highlight.js also.

**Comment by aurelien-reeves** [comment]
Indeed I missed that! I assumed it was actually the case following the PR wich bump highlight.js to v10.4.1: https://github.com/react-syntax-highlighter/react-syntax-highlighter/pull/338

But actually, it just updated package-lock.json. Not package.json.
