### ISSUE TITLE
Update to refractor ^3.3.0 to resolve security vulnerability

### ISSUE THREAD

**Issue by culli** [react-syntax-highlighter/react-syntax-highlighter#366]
GIthub dependabot is reporting a security vulnerability in prismjs < 1.23.0 and refractor >= 3.3.0 updates the prismjs dependency.  This change would be a lot like #318.

https://github.com/wooorm/refractor/releases/tag/3.3.0

https://github.com/advisories/GHSA-h4hr-7fg3-h35w

**Comment by culli** [comment]
Could be partly resolved with #364

**Comment by karlhorky** [comment]
You can already manually upgrade to `3.4.0` (or any 3.x.x version). The caret (the `^`) in the version range means that it will allow any version under v4 (screenshot from [npm semver calculator](https://semver.npmjs.com/)):

<img width="531" alt="Screen Shot 2021-07-04 at 18 06 15" src="https://user-images.githubusercontent.com/1935696/124391811-90889a80-dcf2-11eb-8b21-5c03a292bacd.png">

**Comment by karlhorky** [comment]
If you're using Yarn, you can just remove the `refractor` entry in your lock file, and then run `yarn` again.

Guide here: https://github.com/upleveled/yarn-security-fixes#techniques-to-fix-transitive-dependencies

**Comment by culli** [comment]
Absolutely it can be worked around (I do use yarn and did an upgrade on the needed deps), but why not update the underlying dependency here and help everybody have one less thing to do if they later come to rely on a chain like Storybook -> react-syntax-highlighter -> refractor?

**Comment by karlhorky** [comment]
I agree that `refractor` should be upgraded to the latest version (v4): https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/420

**Comment by simmerer** [comment]
Done in #466 : https://github.com/react-syntax-highlighter/react-syntax-highlighter/pull/466/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by karlhorky** [comment]
Nice, thanks @simmerer ! 🙌 

Will this be published as `react-syntax-highlighter@15.5.1`?
