### ISSUE TITLE
SSR friendly

### ISSUE THREAD

**Issue by Nomyfan** [react-syntax-highlighter/react-syntax-highlighter#390]
**Describe the bug**
React SSR has warning about the HTML structure. It doesn't expect a \<div> in \<span>

**To Reproduce**
Install v15.4.3 and then use the `SyntaxHighlighter` with SSR.

**Expected behavior**
React has no warning

**Screenshots**
<img width="660" alt="snipaste_20210417_003947" src="https://user-images.githubusercontent.com/19922814/115057060-28f25880-9f16-11eb-960f-cd3359637de3.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version v15.4.3

**Additional context**
It seems to be okay when I use the version ^11.0.2 which I use previously.

**Comment by SalahAdDin** [comment]
Is this repository even alive?

**Comment by michaelyuen** [comment]
Can you provide a reproduction?

From the information provided, it is difficult to discern if the problem is with the library or with the usage.

Here's a basic implementation that does not yield the reported issue: https://codesandbox.io/s/react-syntax-highlighter-issue-390-lj5ez

**Comment by Nomyfan** [comment]
Hmm, I have dug out what's wrong. Thx reply.
