### ISSUE TITLE
can not get supportlanguage in typescript?

### ISSUE THREAD

**Issue by liangxiwei** [react-syntax-highlighter/react-syntax-highlighter#400]
**Describe the bug**

**To Reproduce**
SyntaxHighlighter.supportedLanguages in ts file will error.

**Expected behavior**
not error

**Screenshots**
not need

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
not need

**Comment by michaelyuen** [comment]
The type definitions are managed separately from this repository in DefinitelyTyped. Coincidentally, there is an open PR right now to add `supportedLanguages`: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52772

**Comment by SalahAdDin** [comment]
> The type definitions are managed separately from this repository in DefinitelyTyped. Coincidentally, there is an open PR right now to add `supportedLanguages`: [DefinitelyTyped/DefinitelyTyped#52772](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52772)

Why are they handled by a separately repo? Also it seems to be not so much active.

**Comment by michaelyuen** [comment]
> > The type definitions are managed separately from this repository in DefinitelyTyped. Coincidentally, there is an open PR right now to add `supportedLanguages`: [DefinitelyTyped/DefinitelyTyped#52772](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52772)
> 
> Why are they handled by a separately repo? Also it seems to be not so much active.

Well it's one of the two standard approaches: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Off the top of my head:
- Consider users that are not using TypeScript for their projects. They aren't installing code that their projects won't even use.
- Consider libraries that were not originally written in TypeScript. Rewriting the library in TypeScript or augmenting it with TypeScript declarations is not trivial.
- Many library authors or maintainers simply choose not to support TypeScript and that's valid.
- Maintaining them in a separate repo is arguably a nice separation of concerns, allows users of non-TypeScript projects to _not_ install extraneous code or think about it at all, and still allows users of TypeScript projects to easily install the declarations.

> Also it seems to be not so much active.

That's fair. You are more than welcome to help in that regard. The more active the community, the better off we all are. 😃
