### ISSUE TITLE
Please upgrade refractor to 4.1.0

### ISSUE THREAD

**Issue by lanasta** [react-syntax-highlighter/react-syntax-highlighter#414]
The current version is causing dependabot warnings because it’s using the version that employs an older version of prismjs which has security vulnerablilities. Thank you. 

![image](https://user-images.githubusercontent.com/9773638/123705336-d1853880-d834-11eb-82d0-0dcb757bf780.png)

**Comment by josejimenez-swipejobs** [comment]
See issue open on `refractor` https://github.com/wooorm/refractor/issues/41

**Comment by josejimenez-swipejobs** [comment]
This was resolve in the refractor library https://github.com/wooorm/refractor/commit/cecc86b93224d177131e5b700350b37c62f13587. it should be working now.

**Comment by sachinraja** [comment]
It won't be working until this library updates refractor though ([currently on v3.2.0](https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/package.json#L13)).

**Comment by brookemahoney** [comment]
This is working now. refractor released 3.4.0, which fixes this.

**Comment by karlhorky** [comment]
@sachinraja that `^` in the version range means that it will take any version under v4 (screenshot from [npm semver calculator](https://semver.npmjs.com/)):

<img width="531" alt="Screen Shot 2021-07-04 at 18 06 15" src="https://user-images.githubusercontent.com/1935696/124391811-90889a80-dcf2-11eb-8b21-5c03a292bacd.png">

**Comment by karlhorky** [comment]
If you're using Yarn, you can just remove the `refractor` entry in your lock file, and then run `yarn` again.

Guide here: https://github.com/upleveled/yarn-security-fixes#techniques-to-fix-transitive-dependencies

**Comment by sachinraja** [comment]
@karlhorky Thanks, sorry for the confusion. I said that because the package was still showing the security vulnerability after running `npm i react-syntax-highlighter@latest`. Though it is now gone after uninstalling and reinstalling `react-syntax-highlighter`.

**Comment by brookemahoney** [comment]
Prismjs has a new vulnerability, which is fixed in 1.25.0. So, there seems to be no workaround for this issue here at the moment. See https://snyk.io/vuln/SNYK-JS-PRISMJS-1585202 and https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/415#issuecomment-924118820

**Comment by sachinraja** [comment]
That's unfortunate, seems to only affect the markup language though. Could probably solve it with Yarn resolutions, not sure if there's a breaking change that affects this package for refractor 3 to 4 though.
