### ISSUE TITLE
Prismjs vulnerability - level high

### ISSUE THREAD

**Issue by alkistiraft** [react-syntax-highlighter/react-syntax-highlighter#415]
**Describe the bug**
A vulnerability found in prismjs.

**To Reproduce**
Scan for vulnerabilities: yarn audit --level=low --groups=dependencies

**Expected behavior**
The react-syntax-highlighter should have no dependencies with vulnerabilities

**Screenshots**
![image](https://user-images.githubusercontent.com/5869072/124254443-5f10a300-db29-11eb-8223-edc386875135.png)

**Comment by brookemahoney** [comment]
This is being discussed in https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/414

**Comment by char0n** [comment]
There is a new problem with prismjs vulnerability:

```
react-syntax-highlighter@15.4.4 requires prismjs@~1.24.0 via refractor@3.4.0
```

The earliest fixed version of prismjs is 1.25.0. Basically at this point there is no way to fix this.

**Comment by brookemahoney** [comment]
@char0n is right; here's more information: https://snyk.io/vuln/SNYK-JS-PRISMJS-1585202 .

**Comment by karlhorky** [comment]
This was published as part of `react-syntax-highlighter@15.4.5`

**Comment by char0n** [comment]
Great, thanks!

**Comment by karlhorky** [comment]
Thanks goes to @rusackas and @conorhastings !
