### ISSUE TITLE
Highlight all same words on highlighting one

### ISSUE THREAD

**Issue by aayushdutt** [react-syntax-highlighter/react-syntax-highlighter#433]
**Is your feature request related to a problem? Please describe.**
For long code files, it's hard to find where a particular function is used, or where a variable comes from. Having code editor like variable highlight would help a lot for the readers
![image](https://user-images.githubusercontent.com/25280541/139894875-70f12913-7348-42ab-8f4d-c112f08dda38.png)

**Describe the solution you'd like**
Selecting a word (variable/function) should highlight all the occurrences of that word.

**Comment by simmerer** [comment]
This is beyond the scope of what React Syntax Highlighter attempts to do - we're statically recoloring code based on a language definition, whereas what you're describing is very much in the "code editor" realm.

I'd suggest taking a look at [Monaco Editor](https://microsoft.github.io/monaco-editor/), which does this easily.
