### ISSUE TITLE
Last line is always blank also causing an extra line number

### ISSUE THREAD

**Issue by itsrennyman** [react-syntax-highlighter/react-syntax-highlighter#443]
Hello, thank you for this amazing package. As the title says if write something like this:

```bash
$ npm init
```
It will result in something like that

<img width="959" alt="Screenshot 2022-01-15 at 23 59 52" src="https://user-images.githubusercontent.com/9286706/149640336-984dd16c-715f-49dc-ae42-685ba911220c.png">

Is there a way to avoid this issue?

My current configuration is:

```jsx
<SyntaxHighlighter
  language={match[1]}
  PreTag="div"
  style={a11yDark}
  customStyle={{
    padding: 0,
    borderRadius: 0,
    background: "rgba(0,0,0,0.1)",
  }}
  lineNumberStyle={{
    color: "rgba(255,255,255,0.7)",
    marginRight: "0.5rem",
  }}
  wrapLines={true}
  showLineNumbers={true}
  {...props}
/>
```

Many thanks.

**Comment by hoondeveloper** [comment]
+1

**Comment by hoondeveloper** [comment]
It seems that MDX rehype is parsing one more \n unnecessarily.

Temporarily I solved it like this:

```js
children = replaceLast(children, '\n', '');
```

**Comment by itsrennyman** [comment]
> It seems that MDX rehype is parsing one more \n unnecessarily.
> 
> Temporarily I solved it like this:
> 
> ```js
> children = replaceLast(children, '\n', '');
> ```

Thank you for this workaround, currently for me it's ok as a fix.

**Comment by iamludal** [comment]
+1, I'm also facing this issue (with I temporarily fixed too by replacing the last `\n` character)

**Comment by akinolu52** [comment]
you can trim the string before you format it

**Comment by itsrennyman** [comment]
Yes, solved this problem replacing the last \n.

**Comment by iamludal** [comment]
@itsrennyman why did you close the issue as completed? The problem still occurs, we've just fixed it temporarily by removing the last `\n`, but we shouldn't.

As per the [POSIX standard](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206):
> 3.206 Line
> A sequence of zero or more non- <newline> characters plus a terminating <newline> character.

A line should always end with `\n`, so it's not really the job of users to remove it, but the one of this library to not display it.

**Comment by itsrennyman** [comment]
> @itsrennyman why did you close the issue as completed? The problem still occurs, we've just fixed it temporarily by removing the last `\n`, but we shouldn't.
> 
> As per the [POSIX standard](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206):
> 
> > 3.206 Line
> > A sequence of zero or more non-  characters plus a terminating  character.
> 
> A line should always end with `\n`, so it's not really the job of users to remove it, but the one of this library to not display it.

Issue reopened.
