### ISSUE TITLE
Style imports get errors

### ISSUE THREAD

**Issue by emregudur** [react-syntax-highlighter/react-syntax-highlighter#456]
Hi,

I'm using next.js with React, when i import styles in the any component or page, **i refresh page** and i got error.

```js
import { vscDarkPlus, base16AteliersulphurpoolLight } from 'react-syntax-highlighter/dist/esm/styles/prism'
```

eg:
in the pages/post/[id].js

![Error1](https://user-images.githubusercontent.com/41473129/154531465-daccfb9b-936f-4fc4-8a52-6c45f827dcb8.png)

in the my markdown viewer component:

```js
import React from 'react'
import ReactMarkdown from 'react-markdown'
import rehypeRaw from 'rehype-raw'
import remarkGfm from 'remark-gfm'
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'
->>>> import { vscDarkPlus, base16AteliersulphurpoolLight } from 'react-syntax-highlighter/dist/esm/styles/prism' 
import { useColorModeValue } from '@chakra-ui/react'

export default function MarkdownViewer({ raw }) {
  return (
    <ReactMarkdown
      remarkPlugins={[[remarkGfm, { singleTilde: false }]]}
      rehypePlugins={[rehypeRaw]}
      children={raw}
      components={{
        code({ node, inline, className, children, ...props }) {
          const match = /language-(\w+)/.exec(className || '')
          return !inline && match ? (
            <SyntaxHighlighter
              children={String(children).replace(/\n$/, '')}
              style={useColorModeValue(base16AteliersulphurpoolLight, vscDarkPlus)}
              language={match[1]}
              PreTag='div'
              {...props}
            />
          ) : (
            <code className={className} {...props}>
              {children}
            </code>
          )
        },
      }}
    />
  )
}
```

i got this error

![Adsız2](https://user-images.githubusercontent.com/41473129/154532786-ee55585c-a2cc-471a-ad26-657fd7e3cdef.png)

i solved it by copying the styles i needed to my project

**Comment by KatieProchilo** [comment]
I'm getting the same error with create-react-app and TypeScript. Currently trying to solve by running `react-scripts eject` and then modifying the Babel configurations, but really don't want to make that change for a syntax highlighter.

**Comment by KatieProchilo** [comment]
Found the solution in another issue in this repo, you have to import styles from `react-syntax-highlighter/dist/cjs/styles/prism` and languages from `react-syntax-highlighter/dist/cjs/languages/prism/YOUR_LANGUAGE`

So you're changing from `dist/ems/` to `dist/cjs/`

**Comment by emregudur** [comment]
Hi Katie, i tried to changed `dist/ems/` to `dist/cjs/` and worked. Thank you for help 😄
