### ISSUE TITLE
Fix XSS vulnerability by bumping prismjs version

### ISSUE THREAD

**Issue by iamludal** [react-syntax-highlighter/react-syntax-highlighter#461]
**Describe the bug**
Dependabot alerted today that the prismjs library (version >= 1.14.0, < 1.27.0) has an XSS vulnerability. React Syntax Highlighter uses prismjs 1.25.0, that could be upgraded to 1.27.0 in order to fix this vulnerability. See screenshot below.

**Expected behavior**
The prismjs version should be upgraded to 1.27.0.

**Screenshots**
![image](https://user-images.githubusercontent.com/44783088/155838584-ddd33e00-e0c6-48fe-9929-152ed6841c2b.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Comment by icyJoseph** [comment]
Last release was on 2020, I wonder if there's any chance this we'll be released?

**Comment by homotechsual** [comment]
@conorhastings is this maintained active still?

**Comment by icyJoseph** [comment]
Just to be clear, at least for my part, I can try to help with maintenance of the package, but ultimately, it is up to the owners to release any update.

**Comment by stof** [comment]
refractor has backported the prismjs update to their 3.x branch, so you can run `yarn upgrade` and get a patched between thanks to the caret requirement in react-syntax-highlighter.

**Comment by bennycode** [comment]
@conorhastings, @simmerer & @marcodejongh can you please upgrade the "prismjs" dependency? See https://github.com/react-syntax-highlighter/react-syntax-highlighter/pull/459

**Comment by simmerer** [comment]
Hey folks, sorry for being away from this for so long. I'll work on getting another release out this weekend.

**Comment by simmerer** [comment]
15.5.0 is out: https://github.com/react-syntax-highlighter/react-syntax-highlighter/releases/tag/15.5.0
