### ISSUE TITLE
Is it possible to provide a custom theme to ReactSyntaxHighlighter

### ISSUE THREAD

**Issue by ItzaMi** [react-syntax-highlighter/react-syntax-highlighter#478]
Hi all 👋 

Currently using `react-syntax-highlighter` and I would like to personalize one of the themes.
So I thought I could get, for example, the code from [one-dark](https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/src/styles/prism/one-dark.js), paste it in a new file (`theme.js`) and then import it to use it as the value for `style` or even `customStyle`, like this 👇

```jsx
import theme from './theme'

const CodeBlock = () => {
  return (
     <SyntaxHighlighter
      language={language}
      customStyle={theme}
      showLineNumbers={true}
    >
      {code}
    </SyntaxHighlighter>
  )
}
```

However (and I'm not sure if this related more with TypeScript), passing `theme` to `customStyle` or `style` gets me 
`Type '{ 'code[class*="language-"]': { background: string; color: string; textShadow: string; fontFamily: string; direction: string; textAlign: string; whiteSpace: string; wordSpacing: string; wordBreak: string; ... 7 more ...; hyphens: string; }; ... 136 more ...; '.prism-previewer-easing.prism-previewer-easing line': { ....' has no properties in common with type 'Properties<string | number, string & {}>'.`

I came across [this issue](https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/204) and thought that I was able to pass an entire custom style with classes into `customStyle` but maybe I was wrong...

Could someone clarify this for me?

**Comment by redraskal** [comment]
@ItzaMi Your theme file should have a type like below:
```ts
type style = { [key: string]: React.CSSProperties };
export default {
    "hljs-comment": {
        "color": "#d4d0ab"
    },
    "hljs-quote": {
        "color": "#d4d0ab"
    },
    "hljs-variable": {
        "color": "#ffa07a"
    },
    ...
} as style;

```

**Comment by philippwulff** [comment]
Hi, could you please clarify what exactly you mean @redraskal ?

If I copy your code code into `myTheme.ts`:
```
type style = { [key: string]: React.CSSProperties };
export default {
    "hljs-comment": {
        "color": "#d4d0ab"
    },
    "hljs-quote": {
        "color": "#d4d0ab"
    },
    "hljs-variable": {
        "color": "#ffa07a"
    },
    ...
} as style;
```

and then import it as `import theme from './myTheme.ts'`, it does not apply the style in my case. Is it a problem that this is the only TypeScript file in my project? Everything else is JS in my case?

**Comment by redraskal** [comment]
> Hi, could you please clarify what exactly you mean @redraskal ?
> 
> 
> 
> If I copy your code code into `myTheme.ts`:
> 
> ```JavaScript
> 
> type style = { [key: string]: React.CSSProperties };
> 
> export default {
> 
>     "hljs-comment": {
> 
>         "color": "#d4d0ab"
> 
>     },
> 
>     "hljs-quote": {
> 
>         "color": "#d4d0ab"
> 
>     },
> 
>     "hljs-variable": {
> 
>         "color": "#ffa07a"
> 
>     },
> 
>     ...
> 
> } as style;
> 
> ```
> 
> 
> 
> and then import it as `import theme from './myTheme.ts'`, it does not apply the style in my case. Is it a problem that this is the only TypeScript file in my project? Everything else is JS in my case?

Hey, I remember creating a file like this and then using the import with the customStyle prop like in the initial post.

I ended up going with prism and manually set the style with a css file.

**Comment by philippwulff** [comment]
Thanks for your super fast reply :)

I have not thought about doing it that way... do you happen to remember how you styled the different code components? Because when I look at them in the HTML source code from my website react-syntax-highlighter does not apply classnames to variable names, strings, etc.

**Comment by redraskal** [comment]
> Thanks for your super fast reply :)
> 
> I have not thought about doing it that way... do you happen to remember how you styled the different code components? Because when I look at them in the HTML source code from my website react-syntax-highlighter does not apply different classes to variable names, strings, etc (they are all `class="token"`).

No, sorry :( I remember running into performance/styling issues and ended up swapping this with another solution.

Although, this sounds like the highlighter does not recognize the language in your code samples. Maybe you still need to import & reference hljs or prism like in the README https://github.com/react-syntax-highlighter/react-syntax-highlighter#use for the `style` prop?

"token" is the base class for syntax highlighting. each of these elements should have an additional class to denote the type (see https://gist.github.com/redraskal/2374ad67fb808298d139476c185f0029 for examples of prism styles). The styles for this project are likely similar.

If you used the "light" version of the syntax highlighter, you would also need to call the registerLanguage function.
